### ISSUE TITLE
###확인필요###

### ISSUE THREAD

**Issue by Canihelpme** [HUFSummer-Hackathon/Server#1]
1. 현재 DB의 경우 Amazon RDS 사용해서 MYSQL DB Server 생성 및 연결 하였음.
Amazon RDS 연결 및 초기설정에 application.yml 파일 필요하니까 따로 알려드리겠음.
또한, AWS 관리자, 비번도 같이 알려드리겠음.

2. 추후에 EC2 혹은 Elastic Beanstalk 사용해서 APP 구동 계획 중. 결정되면 IAM USER 생성해서 알려드림.

3. Domain은 미리 생성하였음, 그런데 DB 테이블 설계 잘못된것으로 보여 잠시 중단하였음.

4. 초대 빨리 받아서 이거 보시길.

**Comment by chosunghyun18** [comment]
### repo clone 받고 전부 확인했습니다
